version: '3'
services:      
  client:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "80:80"
    
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8000:8000"
